### ISSUE TITLE
failing tests when using spawn-wrap to run node-tap

### ISSUE THREAD

**Issue by bcoe** [isaacs/spawn-wrap#1]
## the bad news

There are failing tests when using nyc to instrument node-tap with code coverage. I think I've hunted down one of the issues:

In the test `expose-gc-test.js`, you run the following shell command:

```shell
bin/run.js --expose-gc ./gc-script.js
```

When this gets spawn wrapped it seems to run `--expose-gc` as `argv[1]`.

```diff
+++ found                                                                            
    --- wanted                                                                           
    -true                                                                                
    +module.js:318                                                                       
    +    throw err;                                                                      
    +          ^                                                                         
    +Error: Cannot find module '/Users/benjamincoe/bcoe/node-tap/--expose-gc'            
    +    at Function.Module._resolveFilename (module.js:316:15)                          
    +    at Function.Module._load (module.js:258:25)                                     
    +    at Function.Module.runMain (module.js:451:10)                                   
    +    at Function.runMain                                                             
    +(/private/tmp/node-spawn-wrap-33830-310e04a7343d/iojs:62:10)                        
    +    at Object.<anonymous>                                                           
    +(/Users/benjamincoe/.nvm/versions/io.js/v1.6.2/lib/node_modules/nyc/bin/nyc.js:14:6)
    +    at Module._compile (module.js:410:26)                                           
    +    at Object.Module._extensions..js (module.js:428:10)                             
    +    at Module.load (module.js:335:32)                                               
    +    at Function.Module._load (module.js:290:12)                                     
    +    at Function.Module.runMain (module.js:451:10)          
```

## the good news

With the updates to nyc's signal handling we now have a much better coverage report for node-tap:

```shell
------------------|-----------|-----------|-----------|-----------|
File              |   % Stmts |% Branches |   % Funcs |   % Lines |
------------------|-----------|-----------|-----------|-----------|
   bin/           |      76.3 |     66.07 |        50 |     76.74 |
      run.js      |      76.3 |     66.07 |        50 |     76.74 |
   lib/           |     86.05 |     80.21 |     91.92 |     86.14 |
      assert.js   |     94.77 |      83.7 |       100 |     95.32 |
      mocha.js    |     85.19 |        70 |        75 |     85.19 |
      root.js     |     77.78 |        25 |         0 |     77.78 |
      stack.js    |     83.78 |      69.7 |       100 |     83.78 |
      synonyms.js |     94.74 |        75 |       100 |     94.74 |
      test.js     |     84.06 |        82 |     90.91 |     84.06 |
------------------|-----------|-----------|-----------|-----------|
All files         |     84.57 |     78.17 |     87.39 |     84.72 |
------------------|-----------|-----------|-----------|-----------|
```

also,

you should now be able to test yourself easily by running:

```shell
npm install nyc -g
nyc npm test
```

## the ugly news

there is no ugly news.

**Comment by isaacs** [comment]
It seems like this got worked out?  tap coverage seems to be working for tap's tests right now?
